# Generated by Django 5.0.4 on 2024-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressId', models.CharField(max_length=10)),
                ('domainName', models.CharField(max_length=30)),
                ('ipv4Address', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=5)),
            ],
        ),
    ]
